### PR TITLE
Quality and Fix 'invalid token' on 2nd screen.

### PR DESCRIPTION
**Pull request by jacquarg**
- cleanup in code to respect cozy-guidelines
- more readable log
- persist log across app life cycle (with the service too).
- add (hacked) mocha test on contact conversion script.
- Fix invalid token / invalid password on 2nd screen with non ascii passwords.

### CODE REVIEW

**Comment by aenario** [comment]
Where does the ContactField class comes from ?
https://github.com/jacquarg/cozy-mobile/blob/dde6ecefa70b2814ba94369ff23a2706daf9c9ac/www-src/app/models/contact.coffee#L46

**Comment by aenario** [comment]
If you have the time, could you also check in tests what happens if there is a malformed cozy contact (wrong number of ;;; in an adr or n). Whith the various versions of the cozy-contacts apps, there are probably a few like that still around !

**Comment by jacquarg** [comment]
ContactField as ContactAddress and ContactName (and ContactOrganisation ...) come from the javascript part of the cordova contact plugin.

In tests, I had to go get them : 
https://github.com/jacquarg/cozy-mobile/blob/dde6ecefa70b2814ba94369ff23a2706daf9c9ac/www-src/test/index.coffee#L4-L9

**Comment by poupotte** [comment]
@aenario , it's now ok for you ?

**Pull request merged**
