### PR TITLE
Smallfixes - daemon, ssl

### PR DESCRIPTION
**Pull request by jacquarg**
* fix settings for daemon
* add message on login on ssl errors

May be added
* fix issue #40 
* no ssl-check option.

### CODE REVIEW

**Comment by aenario** [comment]
If the user is offline, wont the error be the same (SSL certificate inconnu). 
This could prove confusing.
How about replacing this message by a link to an FAQ ?

**Comment by jacquarg** [comment]
Yes you're right thanks ! The '0' status code hide all non-http errors...
I noted :
1 - Offline
2 - Host Unreachable
3 - Invalid Certificat
4 - Unknown Certificat (see [doc](http://cozy.io/en/mobile/files.html#note-about-self-signed-certificates) to add your self-signed cerrtificate).

I could update the message with the one above ? I don't remember any other FAQ than cozy.io/mobile ?
@poupotte  what's your opinion about that ?

**Comment by aenario** [comment]
Mmmh, the full error should read something like : 

> We failed to connect to your cozy. Please check that your phone is connected to the internet and your cozy is running. If you are self hosting, refer to [the doc][http://cozy.io/en/mobile/files.html#note-about-self-signed-certificates] to handle self-signed certificates.

The problem is that the last sentence is scary for a non-technical user.

**Comment by jacquarg** [comment]
Ok for message style, I would had 'check spell on adress', and add 'for advanced user' warning before last part:
> We failed to connect to your cozy. Please check that your phone is connected to the internet, the address of your cozy is spelled correctly and your cozy is running. 
> If you are an advanced user with a self hosted cozy, refer to the [doc](...) to handle self-signed certificates.

**Comment by aenario** [comment]
ok for me, @frankrousseau please validate.

**Comment by poupotte** [comment]
It's ok for me too.

**Pull request merged**
