### PR TITLE
Update Pouchdb and speed optimisations

### PR DESCRIPTION
**Pull request by jacquarg**
- Update PouchDB to 3.3.1 and remove old patch about pouchDB#2517
- Increase speed of image sync (avoid PouchDB query with 'include_docs' flag). Z : with this optimization, _Check if pictures is already present (old installation)_ is now case-insensitive.
- Remove cache in files collection (minimize PouchDB requests).

### CODE REVIEW

**Comment by aenario** [comment]
code wise everything looks good.

Logic wise, just to be sure i understand this : by making this request case-insensitive, if the user have two pictures in a folder with the same name but different cases only one will be synchronized ? If so, I think it is a tradeof we can leave with.

**Comment by jacquarg** [comment]
It's more rare (but also tricky) than that :
If the user re-install the app,
and if he has a new photo with the same name as an old one (previously synchronized) with different case (or not), 
this new picture will not be synchronized.

We may remove this limitation in the future by using case-sensitive filenames in the PouchDB keys we create. As _include_doc_ seems really time consuming (50x on my phone), there is a place to speed up rendering for folders with many files. But it is some work

**Comment by aenario** [comment]
Ok, this is a very very rare case. 
Please open up an issue as a reminder and we will solve it as you mentioned (with a separate index) in the future.

**Comment by aenario** [comment]
Otherwise, this PR is good to merge.

**Comment by poupotte** [comment]
Fonctionally , it seems ok but I don't know if speed optimisations for navigation is better.

**Pull request merged**
